spring:
  datasource:
    username: root  # MySQL 사용자명
    password: ssafy # MySQL 비밀번호

toss:
    secret-key: test_sk_Z61JOxRQVEmWA76RedOzVW0X9bAq  # 토스 시크릿 키
    client-key: test_ck_4yKeq5bgrpLNdm000a1xrGX0lzW6 # 토스 클라이언트 키